### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by OmgImAlexis** [mjs7231/python-plexapi#73]
```
pi@zogg:~ $ cat /home/pi/.pip/pip.log
------------------------------------------------------------
/usr/bin/pip run on Mon Nov 21 05:40:41 2016
Downloading/unpacking plexapi
  Getting page https://pypi.python.org/simple/plexapi/
  URLs to search for versions for plexapi:
  * https://pypi.python.org/simple/plexapi/
  Analyzing links from page https://pypi.python.org/simple/plexapi/
    Found link https://pypi.python.org/packages/01/8e/eca1d9abe0432fef7f6a4c86af558c61631390f35b705a35628ae2bd7f84/PlexAPI-0.2.tar.gz#md5=96f5513802c24a2bc69817ffa976bf18 (from https://pypi.python.org/simple/plexapi/), version: 0.2
    Found link https://pypi.python.org/packages/06/31/0ce446d6717469c8f1cec0c40feacfb587a31d97fb4cc3c79b5a9d4de8e4/PlexAPI-0.9.1.tar.gz#md5=f8093e9ac642e18de6588e4b9fa6eda4 (from https://pypi.python.org/simple/plexapi/), version: 0.9.1
    Found link https://pypi.python.org/packages/0b/92/2c57d5e2d758d0f5f76ed72f7db0f0dad747831009a54c79991491077fa7/PlexAPI-0.2.3.tar.gz#md5=37a9855e49b345978787dd2c57de807b (from https://pypi.python.org/simple/plexapi/), version: 0.2.3
    Found link https://pypi.python.org/packages/0e/6e/56de724747eefe467c42aea34a370afa88a7e90c456eb56aa5ca785fc1ba/PlexAPI-2.0.2.tar.gz#md5=ad898641c7303757d5166df63e9bc872 (from https://pypi.python.org/simple/plexapi/), version: 2.0.2
    Found link https://pypi.python.org/packages/0f/f7/e78b6d8c7292fd64832093631125f0fe21ef9f8e72cd4745a3caa168a95d/PlexAPI-0.9.3.tar.gz#md5=020bed6427b6c5e37bed78b4fd00f3ef (from https://pypi.python.org/simple/plexapi/), version: 0.9.3
    Found link https://pypi.python.org/packages/1d/c9/ef7b641a7359cee899573c21df85028e2fc417ebef2cb96a91646e865e59/PlexAPI-1.1.0.tar.gz#md5=c310e0a3ec58b61aaeee0578b5921c25 (from https://pypi.python.org/simple/plexapi/), version: 1.1.0
    Found link https://pypi.python.org/packages/3a/d0/1a4bd779aa942b0b922981a1a72dcec7728b185cba86b4f6f0c43445f3fd/PlexAPI-0.9.4.tar.gz#md5=8b450b6db481f1174ddc8735d8c0c768 (from https://pypi.python.org/simple/plexapi/), version: 0.9.4
    Found link https://pypi.python.org/packages/45/93/5c3165d8e326ef1788f941d979c46c9267be8f7e42235ab58e8c93e1e602/PlexAPI-1.0.2.tar.gz#md5=9113ba80477ca9576d3557668c7ffbc9 (from https://pypi.python.org/simple/plexapi/), version: 1.0.2
    Found link https://pypi.python.org/packages/4a/98/6b48bfe331ab61c5ccb2d98dcdde09cbdbe5a9a97bc1b662ccd36352a0b3/PlexAPI-0.2.1.tar.gz#md5=2661674d6ee7ef568b4ab53bc24a409d (from https://pypi.python.org/simple/plexapi/), version: 0.2.1
    Found link https://pypi.python.org/packages/9e/93/9b700c5cb93b0a6c4ae6f27b9f900e79c2ef0d8dbb6cca4343e1aac17182/PlexAPI-0.9.2.tar.gz#md5=aa1bf14e2ef35b92e55e3ff4c6f3dd66 (from https://pypi.python.org/simple/plexapi/), version: 0.9.2
    Found link https://pypi.python.org/packages/bc/1a/23318d7ccd1871080e4812cb9ba5b5d2726853a4ae347fc29fb42bc8568b/PlexAPI-0.9.6.tar.gz#md5=9feaecf1abb6836def2d090c647f9424 (from https://pypi.python.org/simple/plexapi/), version: 0.9.6
    Found link https://pypi.python.org/packages/c2/95/fd31295206450678bd55103d05cacf523134f87f151ec979f098d0a345d6/PlexAPI-0.2.2.tar.gz#md5=a0807ef7c53cea582d9203606b5fefab (from https://pypi.python.org/simple/plexapi/), version: 0.2.2
    Found link https://pypi.python.org/packages/c8/5d/6c2bcd44e462a27cfe28bf09aa75236091d92009072327592e4b5eb63288/PlexAPI-1.0.1.tar.gz#md5=d04b5bd6781de6afb9e4394d94c12840 (from https://pypi.python.org/simple/plexapi/), version: 1.0.1
    Found link https://pypi.python.org/packages/c8/dc/6184288312afb6722c39b953338088c842a788348015a56f46b4aaad617c/PlexAPI-1.0.0.tar.gz#md5=8e2c115b0c5732c9f5f1bd061a92a265 (from https://pypi.python.org/simple/plexapi/), version: 1.0.0
    Found link https://pypi.python.org/packages/db/7a/60e8942d5c75b05ccb39cfb8e57f450e8e90e484b651234902e82b0350cc/PlexAPI-0.9.0.tar.gz#md5=44bc040d3b64a897796695fb296a7801 (from https://pypi.python.org/simple/plexapi/), version: 0.9.0
    Found link https://pypi.python.org/packages/e2/11/a09ae8cfb4b999b414468740492a8e033e0c4485ad229f4697fbe58f944f/PlexAPI-2.0.1.tar.gz#md5=14fef6d5a78c4e5b04491e3c65ce2ffd (from https://pypi.python.org/simple/plexapi/), version: 2.0.1
  Using version 2.0.2 (newest of versions: 2.0.2, 2.0.1, 1.1.0, 1.0.2, 1.0.1, 1.0.0, 0.9.6, 0.9.4, 0.9.3, 0.9.2, 0.9.1, 0.9.0, 0.2.3, 0.2.2, 0.2.1, 0.2)
  Downloading PlexAPI-2.0.2.tar.gz
  Downloading from URL https://pypi.python.org/packages/0e/6e/56de724747eefe467c42aea34a370afa88a7e90c456eb56aa5ca785fc1ba/PlexAPI-2.0.2.tar.gz#md5=ad898641c7303757d5166df63e9bc872 (from https://pypi.python.org/simple/plexapi/)
  Running setup.py (path:/tmp/pip-build-POcDDg/plexapi/setup.py) egg_info for package plexapi
    Warn: pypandoc not found, not converting Markdown to RST
    running egg_info
    creating pip-egg-info/PlexAPI.egg-info
    writing requirements to pip-egg-info/PlexAPI.egg-info/requires.txt
    writing pip-egg-info/PlexAPI.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/PlexAPI.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/PlexAPI.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/PlexAPI.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found
    
    reading manifest file 'pip-egg-info/PlexAPI.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'pip-egg-info/PlexAPI.egg-info/SOURCES.txt'
  Source in /tmp/pip-build-POcDDg/plexapi has version 2.0.2, which satisfies requirement plexapi
Requirement already satisfied (use --upgrade to upgrade): requests in /usr/lib/python2.7/dist-packages (from plexapi)
  skipping extra security
  skipping extra security
  skipping extra security
Installing collected packages: plexapi
  Running setup.py install for plexapi
    Running command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-POcDDg/plexapi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-DPT_pI-record/install-record.txt --single-version-externally-managed --compile
    Warn: pypandoc not found, not converting Markdown to RST
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-armv7l-2.7
    creating build/lib.linux-armv7l-2.7/tests
    copying tests/examples.py -> build/lib.linux-armv7l-2.7/tests
    copying tests/utils.py -> build/lib.linux-armv7l-2.7/tests
    copying tests/tests.py -> build/lib.linux-armv7l-2.7/tests
    copying tests/__init__.py -> build/lib.linux-armv7l-2.7/tests
    copying tests/findattrs.py -> build/lib.linux-armv7l-2.7/tests
    creating build/lib.linux-armv7l-2.7/plexapi
    copying plexapi/config.py -> build/lib.linux-armv7l-2.7/plexapi
    copying plexapi/myplex.py -> build/lib.linux-armv7l-2.7/plexapi
    copying plexapi/compat.py -> build/lib.linux-armv7l-2.7/plexapi
    copying plexapi/playlist.py -> build/lib.linux-armv7l-2.7/plexapi
    copying plexapi/server.py -> build/lib.linux-armv7l-2.7/plexapi
    copying plexapi/sync.py -> build/lib.linux-armv7l-2.7/plexapi
    copying plexapi/video.py -> build/lib.linux-armv7l-2.7/plexapi
    copying plexapi/audio.py -> build/lib.linux-armv7l-2.7/plexapi
    copying plexapi/utils.py -> build/lib.linux-armv7l-2.7/plexapi
    copying plexapi/client.py -> build/lib.linux-armv7l-2.7/plexapi
    copying plexapi/__init__.py -> build/lib.linux-armv7l-2.7/plexapi
    copying plexapi/exceptions.py -> build/lib.linux-armv7l-2.7/plexapi
    copying plexapi/media.py -> build/lib.linux-armv7l-2.7/plexapi
    copying plexapi/library.py -> build/lib.linux-armv7l-2.7/plexapi
    copying plexapi/photo.py -> build/lib.linux-armv7l-2.7/plexapi
    copying plexapi/playqueue.py -> build/lib.linux-armv7l-2.7/plexapi
    running install_lib
    creating /usr/local/lib/python2.7/dist-packages/tests
    error: could not create '/usr/local/lib/python2.7/dist-packages/tests': Permission denied
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-POcDDg/plexapi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-DPT_pI-record/install-record.txt --single-version-externally-managed --compile:
    Warn: pypandoc not found, not converting Markdown to RST

running install

running build

running build_py

creating build

creating build/lib.linux-armv7l-2.7

creating build/lib.linux-armv7l-2.7/tests

copying tests/examples.py -> build/lib.linux-armv7l-2.7/tests

copying tests/utils.py -> build/lib.linux-armv7l-2.7/tests

copying tests/tests.py -> build/lib.linux-armv7l-2.7/tests

copying tests/__init__.py -> build/lib.linux-armv7l-2.7/tests

copying tests/findattrs.py -> build/lib.linux-armv7l-2.7/tests

creating build/lib.linux-armv7l-2.7/plexapi

copying plexapi/config.py -> build/lib.linux-armv7l-2.7/plexapi

copying plexapi/myplex.py -> build/lib.linux-armv7l-2.7/plexapi

copying plexapi/compat.py -> build/lib.linux-armv7l-2.7/plexapi

copying plexapi/playlist.py -> build/lib.linux-armv7l-2.7/plexapi

copying plexapi/server.py -> build/lib.linux-armv7l-2.7/plexapi

copying plexapi/sync.py -> build/lib.linux-armv7l-2.7/plexapi

copying plexapi/video.py -> build/lib.linux-armv7l-2.7/plexapi

copying plexapi/audio.py -> build/lib.linux-armv7l-2.7/plexapi

copying plexapi/utils.py -> build/lib.linux-armv7l-2.7/plexapi

copying plexapi/client.py -> build/lib.linux-armv7l-2.7/plexapi

copying plexapi/__init__.py -> build/lib.linux-armv7l-2.7/plexapi

copying plexapi/exceptions.py -> build/lib.linux-armv7l-2.7/plexapi

copying plexapi/media.py -> build/lib.linux-armv7l-2.7/plexapi

copying plexapi/library.py -> build/lib.linux-armv7l-2.7/plexapi

copying plexapi/photo.py -> build/lib.linux-armv7l-2.7/plexapi

copying plexapi/playqueue.py -> build/lib.linux-armv7l-2.7/plexapi

running install_lib

creating /usr/local/lib/python2.7/dist-packages/tests

error: could not create '/usr/local/lib/python2.7/dist-packages/tests': Permission denied

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-POcDDg/plexapi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-DPT_pI-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-POcDDg/plexapi
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 295, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1436, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 707, in install
    cwd=self.source_dir, filter_stdout=self._filter_install, show_stdout=False)
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 716, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-POcDDg/plexapi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-DPT_pI-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-POcDDg/plexapi
```

**Comment by OmgImAlexis** [comment]
You may want to change the README to state sudo needs to be used when installing.

**Comment by mjs7231** [comment]
Thanks OmgImAlexis; marking this one as a documentation issue.

**Comment by mjs7231** [comment]
I think this might be a bug and not a doc issue.  We shouldn't need root access to install. We also shouldn't be doing anything with the test folder during install.

**Comment by mjs7231** [comment]
commit 313fef4de80fec5a187f71b76e53c3333efcb2fd
Author: Michael Shepanski <mjs7231@gmail.com>
Date:   Mon Jan 9 01:52:46 2017 -0500
Only include the plexapi package when running setup
