### ISSUE TITLE
Refresh on a show is not working

### ISSUE THREAD

**Issue by advorsky73** [mjs7231/python-plexapi#98]
Hi...

Verified against PMS running on NVIDIA Shield:
```
odaat = plex.library.section('Serien Deutsch').get('One Day at a Time (2017)')
odaat.refresh()
```

gives

```
Traceback (most recent call last):
  File "C:\Temp\PlexLister.py", line 30, in <module>
    odaat.refresh()
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\plexapi\video.py", line 164, in refresh
    self.server.query('/library/metadata/%s/refresh' % self.ratingKey)
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\plexapi\server.py", line 110, in query
    raise BadRequest('(%s) %s' % (response.status_code, codename))
plexapi.exceptions.BadRequest: (405) method_not_allowed
```

**Comment by Hellowlol** [comment]
Thanks.

**Comment by advorsky73** [comment]
got the solution from plex forums: https://forums.plex.tv/discussion/comment/1353252 
it has to be a PUT not a GET to work!
verified with CURL:
```
C:\Temp>curl -k -X PUT https://xxxx:32400/library/metadata/135268/refresh?X-Plex-Token=xxxxxxx
<?xml version="1.0" encoding="UTF-8"?>
<MediaContainer size="0" identifier="com.plexapp.plugins.library" mediaTagPrefix="/system/bundle/media/flags/" mediaTagVersion="1482655637">
</MediaContainer>
```

**Comment by Hellowlol** [comment]
This is has been fixed in my reponses branch.

**Comment by mjs7231** [comment]
Responses branch merged and a test for this function is added and passing: test_video_Show_refresh

commit 6e761f0fc5bf026e5ef980a884f8e9e0f3a8af09
Merge: 5f9c230 e2efc5f
Author: Michael Shepanski <mjs7231@gmail.com>
Date:   Wed Feb 1 22:05:59 2017 -0500
Merge pull request #100 from Hellowlol/responses
Responses
